spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: tiger

    dbcp2:
     min-idle: 5             # 数据库连接池的最小维持连接数
     initial-size: 5         # 初始化连接数
     max-total: 5            # 最大连接数
     max-wait-millis: 200    # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybaits.cfg.xml
  type-aliases-package: cn.com.cloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

info:
  app.name: microservicecloud-springcloudconfig02
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}